#!/bin/sh

### BEGIN INIT INFO
# Provides:          astra
# Required-Start:    $network $syslog $named
# Required-Stop:     $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop astra
### END INIT INFO

set -e

if [ -z "$1" ] ; then
    echo "Usage: $0 [start|stop|restart]"
    exit 0
fi

if [ "$1" = "start" ] ; then
    ulimit -n 65536
    /usr/bin/astra --pid /var/run/astra.pid --log /var/log/astra.log -c /etc/astra/astra.conf -p 8080 --daemon
elif [ "$1" = "stop" ] ; then
    kill `cat /var/run/astra.pid`
elif [ "$1" = "restart" ] ; then
    $0 stop
    sleep 1
    $0 start
fi
